# These are supported funding model platforms

github: fjy202# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: fjy202# Replace with a single Patreon username
open_collective: fjy202# Replace with a single Open Collective username
ko_fi: fjy202# Replace with a single Ko-fi username
tidelift: pypi/WeChat-Linux# Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: WeChat-Linux# Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: fjy202# Replace with a single Liberapay username
issuehunt: fjy202# Replace with a single IssueHunt username
otechie: fjy202# Replace with a single Otechie username
custom: https://github.com/fjy202/WeChat-Linux/.github/coffee.jpg# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
