# These are supported funding model platforms

github: fjy202# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: https://github.com/fjy202/WeChat-Linux/blob/master/.github/coffee.jpg
